### PR TITLE
Sign and notarize macOS workflow artifact

### PR DESCRIPTION
**Pull request by valentinegb**
This pull request aims to integrate signing and notarization into the macOS portion of the build workflow. It has been created before it is ready to be merged because this is something I can't test on my local machine and so heavy review is necessary.

The changes made require new GitHub secrets to be created. They are as follows:

- `BUILD_CERTIFICATE_BASE64`: This is the `p12` certificate file. Use the following command to convert your certificate to Base64 and copy it to your clipboard:
  ```
  base64 -i BUILD_CERTIFICATE.p12 | pbcopy
  ```
- `P12_PASSWORD`: The password for the Apple signing certificate.
- `BUILD_PROVISION_PROFILE_BASE64 `: The Apple provisioning profile. Use the following command to convert your provisioning profile to Base64 and copy it to your clipboard:
  ```
  base64 -i PROVISIONING_PROFILE.provisionprofile | pbcopy
  ```
- `KEYCHAIN_PASSWORD`: A keychain password. A new keychain will be created on the runner, so the password for the new keychain can be any new random string.
- `APPLE_ID`: The Apple ID associated with the developer account.
- `APPLE_TEAM_ID`: The Apple Developer account team ID.
- `APPLE_APP_SPECIFIC_PASSWORD`: A 2FA password for this specific app. See [Using app-specific passwords](https://support.apple.com/en-us/HT204397).

Before approving the workflow for this pull request, remember that it will certainly fail unless these GitHub secrets have been properly set.

[This GitHub Docs page](https://docs.github.com/en/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development) was used for reference.

### CODE REVIEW

**Comment by fire** [comment]
I'll get to this when I can. I don't think today is the day :(

**Comment by valentinegb** [comment]
> I'll get to this when I can. I don't think today is the day :(

Not a problem ^^

**Comment by fire** [comment]
So to be clear I get an apple developer account, get the key in a text form, and put it into the secrets section?

**Comment by valentinegb** [comment]
I'm not familiar with the Apple Developer dashboard interface, but I think you can download a certificate. Then use the commands I provided to encode it and copy it as text to your clipboard.

**Comment by valentinegb** [comment]
This article may be helpful: https://developer.apple.com/help/account/create-certificates/create-developer-id-certificates/

**Comment by valentinegb** [comment]
From various sources online it looks like you can import the `.cert` file from that article into Keychain and export a `.p12` file

**Comment by fire** [comment]
The other update affected this pull request.

**Comment by fire** [comment]
@Ughuuu has been helping me get signing into Godot Engine

**Comment by valentinegb** [comment]
Hey, sorry it's been a while, I had to completely wipe my computer a while ago and to be honest I totally forgot about this pull request ^^'
I'm a bit busy with some other projects now unfortunately but I'll leave all my code up in case someone else wants to pick this back up
I may work on this again in the future, but not now, sorry

**Comment by Ughuuu** [comment]
Made

**Pull request closed without merging**
