### PR TITLE
Access files using UTF-8 encoding

### PR DESCRIPTION
**Pull request by hu-xd**
file names in FBX are encoded as UTF-8 and mustbe accessed properly, especially on Windows.

### CODE REVIEW

**Comment by fire** [comment]
Do you think it's possible to use only std from c++? I'm curious.

**Comment by hu-xd** [comment]
its 'possible' to using std but that would be a lot more messy, boost::nowide is designed specifically as a drop in replacement for std to solve UTF-8 problems, especially on Windows. and nowide is integrated with boost::filesystem which is already in use here.

**Review by fire — APPROVED** [review]
It looks good to me, but can you squash to one commit. I'll see if I can get @bruvzg to take a look.

**Comment by hu-xd** [comment]
oh thank you! I didn't find time to fix this :-)

**Review by lyuma — APPROVED** [review]

**Review by lyuma — APPROVED** [review]

**Comment by fire** [comment]
Thanks!

**Pull request closed without merging**
